name: Publish package to GitHub Packages

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          registry-url: "https://npm.pkg.github.com"
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn install
      - name: Build package
        run: yarn build:lib
      - name: Publish package
        run: yarn deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}